Beginner Example from https://www.tensorflow.org/tutorials/quickstart/beginner

In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [4]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2964 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1414 - accuracy: 0.9575
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1066 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0851 - accuracy: 0.9741
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0732 - accuracy: 0.9771


In [6]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0784 - accuracy: 0.9757


[0.07841803878545761, 0.9757000207901001]

In [7]:
model.predict(x_test[:1])

array([[ -4.0980043 ,  -7.4098196 ,   0.29941168,   2.2055953 ,
        -10.781264  ,  -5.446631  , -16.462194  ,  12.929349  ,
         -6.02154   ,  -3.0151849 ]], dtype=float32)

In [8]:
tf.nn.softmax(model.predict(x_test[:1]))

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[4.0281289e-08, 1.4682509e-09, 3.2724793e-06, 2.2015154e-05,
        5.0419720e-11, 1.0456878e-08, 1.7195048e-13, 9.9997449e-01,
        5.8846705e-09, 1.1895033e-07]], dtype=float32)>

In [9]:
y_test[:1]

array([7], dtype=uint8)